interface ApiConfigType {
  CONTENTFUL_ACCESS_TOKEN: string;
  CONTENTFUL_ENVIRONMENT: string;
  CONTENTFUL_SPACE_ID: string;
}

const API_CONFIG: ApiConfigType = {
	CONTENTFUL_ACCESS_TOKEN: "wO9AhZ3Ig3-aFGAJ3SEj1vtKJ6DuYhvnwDHTJfsQX5w",
	CONTENTFUL_ENVIRONMENT: "master",
	CONTENTFUL_SPACE_ID: "ojpqlra32uom"
};

export default API_CONFIG;
